### ISSUE TITLE
Add CodeQL workflow

### ISSUE THREAD

**Issue by stv0g** [pion/.goassets#108]
The transport module has a CodeQL GitHub workflow as can be found here: https://github.com/pion/transport/blob/master/.github/workflows/codeql-analysis.yml

I do not see this workflow in this repo.
Should we add it to goassets as well?
Or is it obsolete and can be removed from the transport module?

**Comment by at-wat** [comment]
That workflow is synced from here: https://github.com/pion/.goassets/blob/master/ci/.github/workflows/codeql-analysis.yml
but lacking `DO NOT EDIT THIS FILE` header.

**Comment by stv0g** [comment]
Thanks. I assume we can close this after the last PR has been merged :)
