### ISSUE TITLE
Undefined environment variable GITHUB_WORKSPACE

### ISSUE THREAD

**Issue by stv0g** [pion/.goassets#109]
I am wondering where the `GITHUB_WORKSPACE` env variable is set?

See: https://github.com/pion/.goassets/blob/master/ci/.github/generate-authors.sh#L15

**Comment by ashellunts** [comment]
It is set by GitHub Actions
https://docs.github.com/en/actions/learn-github-actions/environment-variables

**Comment by stv0g** [comment]
Thanks @ashellunts,

I think this breaks when the script is invoked via a local Git hook.

I will create a PR to set the workspace to the Git worktree when used outside a GitHub CI workflow.
