### ISSUE TITLE
Allow single line commit messages

### ISSUE THREAD

**Issue by stv0g** [pion/.goassets#143]
Its one of the major reasons new contributions are failing the CI for..

**Comment by ashellunts** [comment]
I support the suggestion.

**Comment by at-wat** [comment]
I basically second this, but we also should check commits just saying `Bug fix` on review

**Comment by Sean-Der** [comment]
I support as well! Could we switch to https://www.conventionalcommits.org/en/v1.0.0/ ?

Then we could also generate nice CHANGELOGs. Users want to know what is in a new commit (bugs, features etc..)

**Comment by stv0g** [comment]
I like the idea of the conventional commits spec. Especially, because we could get rid of our own script to validate the commit messages.

**Comment by ashellunts** [comment]
I have found this go tool (https://github.com/aevea/commitsar) to check for conventional commit compliance.
Pro: it has GitHub actions support. Con: dependency to install when running locally.

How are we going to handle renovate bot commit messages that are not compliant with conventional commit style?

**Comment by at-wat** [comment]
> How are we going to handle renovate bot commit messages that are not compliant with conventional commit style?

Renovate supports conventional commit message
https://docs.renovatebot.com/semantic-commits/
