### ISSUE TITLE
Pass Codecov upload token to codecov/codecov-action

### ISSUE THREAD

**Issue by at-wat** [pion/.goassets#193]
https://github.com/codecov/codecov-action?tab=readme-ov-file#v4-release
> ## Breaking Changes
> - Tokenless uploading is unsupported. However, PRs made from forks to the upstream public repos will support tokenless (e.g. contributors to OS projects do not need the upstream repo's Codecov token)

TODO
- [ ] Generate Codecov Global Upload Token as pionbot account
- [ ] Store Global Upload Token in [organization secrets](https://github.com/organizations/pion/settings/secrets/actions)
- [ ] Pass token to codecov/codecov-action

**Comment by Sean-Der** [comment]
@at-wat Do you want me to push the revert/take your changes and deploy them?

**Comment by at-wat** [comment]
My branch contains debug logging, so please revert them directly

**Comment by at-wat** [comment]
@Sean-Der My branch contains debug logging, so please revert them directly
