### ISSUE TITLE
Blacklist usage of testify/assert

### ISSUE THREAD

**Issue by Sean-Der** [pion/.goassets#206]
What do you think of requiring `require` everywhere @stv0g 

I am merging your change that does this in pion/ice, seems like a good idea to be consistent!

**Comment by stv0g** [comment]
Hey @Sean-Der,

I am not so sure about it as its not always desired to immediatly abort a test.
Sometimes we are doing table-like tests in a single test using loops to test various combination of parameters.
If we would use `require` in this case, we would abort the parametrized test case on the first failing parameter combination.

**Comment by Sean-Der** [comment]
What about allowing the lint to be disabled on a line basis?

I am taking a bunch of your ice improvement. Would love to see them propagate out across all the repos and be consistent
