### ISSUE TITLE
lint-commit-message.sh is not working on GitHub Actions

### ISSUE THREAD

**Issue by at-wat** [pion/.goassets#47]
The script requires `TRAVIS_COMMIT_RANGE` environment variable.

https://github.com/pion/.goassets/blob/326ae6400391dd6611743cc755e7c45983e6f755/.github/workflows/lint.yml#L23-L35
Above hack emulates `TRAVIS_COMMIT_RANGE` environment variable. (I'm not very sure it covers all situations.)

**Comment by at-wat** [comment]
FYI @Sean-Der @tarrencev

**Comment by Sean-Der** [comment]
Fixed with c162720a234ce5d083cb1de4af7e8d658735830f

Thanks for catching this @at-wat :)
