### ISSUE TITLE
Blacklist github.com/pkg/errors (maybe?)

### ISSUE THREAD

**Issue by Sean-Der** [pion/.goassets#48]
It doesn't seem like we are getting much value from using this library. I vote drop it. It is used in pion/quic and pion/sctp

@scorpionknifes @enobufs Yay/Nay?

**Comment by scorpionknifes** [comment]
I actually didn't catch that. Just double-checking, ```github.com/pkg/errors``` is used for compatibility? I don't see a problem blacklisting it.

**Comment by scorpionknifes** [comment]
No idea where pion/quic uses ```github.com/pkg/errors```. Thought it was ```github.com\lucas-clemente\quic-go``` but they also seem to also not use it?
