### ISSUE TITLE
Automerge renovate PRs if they pass

### ISSUE THREAD

**Issue by Sean-Der** [pion/.goassets#59]
What do you think @at-wat? I am not auditing anything if the build passes personally. 

It is just taking more developer time/making the project look bad when we have open PRs.

**Comment by at-wat** [comment]
I think automerge is good only for the repository with almost 100% test coverage.

Go official packages like `golang.org/x/net` would be ok because of Go 1 promise of compatibility.

**Comment by Sean-Der** [comment]
Done with 8a5466ce84ccbc14bab681ea4a7bb9c0b248b802

We can rollback if it is a problem. I am the only one who merges these, and I am not actively reviewing if all the tests pass.
